/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package application;

public class App {

    public static void main(String[] args) {
        Application app = new Application();
        app.run();
    }
}
